spring.application.name=backend

# Conexión a la DB remota en Railway
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

# JWT
clave.secreta.jwt=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Otros parámetros opcionales
issue.generator=MIPCLOCAL
